import { Footer } from '@/components/layout/footer';
import { league_spartan } from '@/lib/styles/fonts';
import '@/lib/styles/globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Dine Restaurant',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${league_spartan.variable} font-league-spartan antialiased`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
